config/routes.rb
WebBasedTeachersSubstitutionSystem::Application.routes.draw do

  get "confirm_substitutions/index"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  
  resources :sessions

  resources :teacher_schedules
  resources :substitution_records
  resources :substitutes do
    get :load_teacher_subject, on: :collection
    get :load_sub_teacher_subjects, on: :collection
    get :load_available_teachers, on: :collection
  end
  resources :confirm_substitutions
  resources :generate_reports
  
  resources :remind_substitutes do
    resources :request_details
  end
  
  resources :vouch_requests
  resources :verify_requests
  
  scope '/maintenance' do
    resources :import_schedules, only: [ :index, :create ]
    resources :users
    resources :departments
    resources :teachers
    resources :subjects
    resources :reasons
    resources :daycodes
    resources :sections
    resources :rooms  
    resources :subject_types
  end
  

  

  root :to =>'dashboard#show'

end

app/views/shared/_navigation.html.erb
<div id="sidebar">		
			
	<ul id="mainNav">			
		<li id="navDashboard" class="nav active">
			<span class="icon-home"></span>
			<%= link_to 'Dashboard', root_path %>
		</li>
		
		<li id="navTables" class="nav">
			<span class="icon-list"></span>
			<%= link_to "Teacher's Schedule", teacher_schedules_path %>
		</li>



		<li id="navForms" class="nav">
			<span class="icon-document-alt-stroke"></span>
			<a href="javascript:;">Department Head</a>
			
			<ul class="subNav">
				<li id="navTables" class="nav">
					<%= link_to 'Request Substitution', request_substitutions_path %>
				</li>		

				
				<li id="navTables" class="nav">
					<%= link_to 'Vouch Request',  request_substitutions_path %>
				</li>	

				<li id="navTables" class="nav">
					<%= link_to 'Remind Request',  request_substitutions_path %>
				</li>		

			</ul>		
		</li>


		<li id="navForms" class="nav">
			<span class="icon-document-alt-stroke"></span>
			<a href="javascript:;">Checker</a>
			
			<ul class="subNav">
				<li id="navTables" class="nav">
					<%= link_to 'Verify Request', generate_reports_path %>
				</li>	

				<li id="navTables" class="nav">
					<%= link_to 'Vouch Request', generate_reports_path %>
				</li>	

				<li id="navTables" class="nav">
					<%= link_to 'Genereate Reports', generate_reports_path %>
				</li>		
			</ul>	
		</li>

		
		<li id="navTables" class="nav">
			<span class="icon-info"></span>
			<%= link_to 'Substitution Record', substitution_records_path %>
		</li>



		<li id="navForms" class="nav">
			<span class="icon-document-alt-stroke"></span>
			<a href="javascript:;">Maintenance</a>
			
			<ul class="subNav">
				
				<li id="navTables" class="nav">
					<%= link_to 'User Accounts', users_path %>
				</li>		
				
				<li id="navTables" class="nav">
					<%= link_to ' User Department', departments_path %>
				</li>		
				
				<li id="navTables" class="nav">
					<%= link_to 'Teachers', teachers_path %>
				</li>		

					<li id="navTables" class="nav">
					<%= link_to 'Subjects', subjects_path %>
				</li>		

				<li id="navTables" class="nav">
					<%= link_to ' Absent Reason', reasons_path %>
				</li>	

				<li id="navTables" class="nav">
					<%= link_to 'Import Teacher Schedule', import_schedules_path %>
				</li>		
							
			</ul>		
		</li>

	</ul>
	
	
	
	
	
</div> <!-- #sidebar -->