config/routes.rb
WebBasedTeachersSubstitutionSystem::Application.routes.draw do

  get "confirm_substitutions/index"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  
  resources :sessions

  resources :teacher_schedules
  resources :substitution_records
  resources :substitutes do
    get :load_teacher_subject, on: :collection
    get :load_sub_teacher_subjects, on: :collection
    get :load_available_teachers, on: :collection
  end
  resources :confirm_substitutions
  resources :generate_reports
  
  resources :remind_substitutes do
    resources :request_details
  end
  
  resources :vouch_requests
  resources :verify_requests
  
  scope '/maintenance' do
    resources :import_schedules, only: [ :index, :create ]
    resources :users
    resources :departments
    resources :teachers
    resources :subjects
    resources :reasons
    resources :daycodes
    resources :sections
    resources :rooms  
    resources :subject_types
  end
  

  

  root :to =>'dashboard#show'

end

app/models/reason.rb
class Reason < ActiveRecord::Base

	scope :search_by_name, lambda { | value | where("CONCAT(name) LIKE ?", "%#{value}%")}

	validates :name, presence: true

def self.search(search)

	reason_scope = self.scoped({})

	reason_scope = reason_scope.search_by_name(search) if search.present?

	return reason_scope
end
end

app/controllers/reasons_controller.rb
class ReasonsController < ApplicationController
  
  def index
    @reasons = Reason.search(params[:search]).page(params[:page]).per(10)
  end

  def show
  	@reason = Reason.find(params[:id])
  end

  def new
  	@reason = Reason.new
  end

  def create
  	@reason = Reason.create(params[:reason])

  	if @reason.save
  		redirect_to reasons_path, notice: "Absent Reasons is Successfully Added!"
  	else
  		render :new
  	end

  end

  def edit
  	@reason = Reason.find(params[:id])

  end

  def update
  	@reason = Reason.find(params[:id])

  	if @reason.update_attributes(params[:reason])
  		redirect_to reasons_path, notice: "Absent Reasons is Successfully Updated!"
  	else
  		render :edit
  	end

  end

  def destroy
  	@reason = Reason.find(params[:id])
  	@reason.destroy

  	redirect_to reasons_path, notice: "Successfully Deleted!!"

  end

end

app/helpers/reasons_helper.rb
module ReasonsHelper
end

app/views/reasons/_form.html.erb
<div class="field-group inlineField " style="float:left;">	
	<div class="field">
		<label for="name">Reason :</label>
		<%= f.text_field :name, size: 24, placehold: 'Reason' %>
	</div>
	<br/>
</div>

app/views/reasons/_reasons.erb
<tr>
	<td><%= reason.name %></td>
	<td>
		<%= link_to edit_reason_path(reason) do %>
			<button class="btn btn-primary btn-blue">Edit</button>
		<% end %>
		<div class="delete">
		<%= button_to "delete", reason_path(reason), :method=>:delete, :class=>"btn btn-primary btn-blue" %>
		</div>
	</td>	
</tr>

app/views/reasons/edit.html.erb
<div id="content">			
	<div id="contentHeader">
		<h1>Edit reason</h1>
	</div> <!-- #contentHeader -->	
	<div class="container">
		<div class="grid-24">
			<%= form_for @reason, :method => :put do |f| %>

				<% if @reason.errors.present? %>
					<div class="alert alert-error">
						<a class="close" href="javascript:;">×</a>
						
						<% for msg in @reason.errors.full_messages %>
		          <%= content_tag :div, msg %>
		        <% end %>
							
				</div>
				<% end %>
				<div class="form uniformForm">					
					<div class="widget">
						<div class="widget-header">
							<h3>Reason Information</h3>
						</div>
						<div class="widget-content">
							<%= render 'form', f: f %>
						</div> <!-- .widget-content -->
					</div> <!-- .widget -->
						
				</div>
				<div class="fmenu">
					<br style="clear:both;">
						
						<%= link_to 'Cancel', reasons_path, class: 'btn btn-primary btn-blue'  %>
						<button class="btn btn-primary btn-blue">Save</button>
				</div>
			<% end %>
		</div>
	</div> <!-- .grid -->			
</div>
			
			

app/views/reasons/index.html.erb
<div id="content">			
	<div id="contentHeader">
		<h1>Reasons Information</h1>
	</div> <!-- #contentHeader -->	
	<div class="container">
		<div class="grid-24">
			<% if notice %>
				<div class="alert alert-success">
							<a class="close" href="javascript:;">×</a>
							<%= notice %>
				</div>
			<% end %>

			<div class="adduser">
				<%= link_to new_reason_path do %>
					<button class="btn btn-primary btn-blue">Add Reasons
					</button>
				<% end %>
				
			</div>

			<div class="widget widget-table">
				<div class="widget-header">
					<h3 class="icon chart">Reasons Lists</h3>		
				</div>
				
				<div class="widget-content">
					<%= form_for reasons_path, method: :get do %>
						<div class="search">
							<div class="field">
								<%= text_field_tag :search, params[:search], size: 24 , :Placeholder => "Search"%>
								<%= submit_tag "search", :name => nil, :class => "btn btn-primary btn-blue" %>
							</div>
						</div>
					<% end %>
					<table  id="my-table" class="table table-bordered table-striped data-table">
						<thead>
							<tr>
								<th>Reasons</th>
								<th>Action</th> 
							</tr>
						</thead>
				   		 <tbody>
								<%= render partial: 'reasons', collection: @reasons, as: :reason %>
				    	</tbody>
         			</table>
         			<%= paginate @reasons %>
				</div> <!-- .widget-content -->
			   </div> <!-- .widget -->
			</div> <!-- .widget-content -->
		</div> <!-- .widget -->	
	</div> <!-- .grid -->			
</div>
			
<!-- refresh plugin search -->
<script type="text/javascript" src="/assets/jquerysearch.js"></script>

app/views/reasons/new.html.erb
<div id="content">			
	<div id="contentHeader">
		<h1>Create Reason</h1>
	</div> <!-- #contentHeader -->	
	<div class="container">
		<div class="grid-24">
			
			<%= form_for @reason, url: reasons_path,  method: :post do |f| %>
			
				<% if @reason.errors.present? %>
					<div class="alert alert-error">
						<a class="close" href="javascript:;">×</a>
						
						<% for msg in @reason.errors.full_messages %>
		          <%= content_tag :div, msg %>
		        <% end %>
							
					</div>
				<% end %>
				
				<div class="form uniformForm">					
					<div class="widget">
						<div class="widget-header">
							<h3>Reason Information</h3>
						</div>
						<div class="widget-content">
							<%= render 'form', f: f %>
						</div> <!-- .widget-content -->
					</div> <!-- .widget -->
					 
				</div>
				<div class="fmenu">
					<br style="clear:both;">
						
						<%= link_to 'Cancel', reasons_path, class: 'btn btn-primary btn-blue'  %>
						<button class="btn btn-primary btn-blue">Save</button>
				</div>
				
			<% end %>
		</div>
	</div> <!-- .grid -->			
</div>
			
			