config/routes.rb
WebBasedTeachersSubstitutionSystem::Application.routes.draw do

  get "confirm_substitutions/index"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  
  resources :sessions

  resources :teacher_schedules
  resources :substitution_records
  resources :substitutes do
    get :load_teacher_subject, on: :collection
    get :load_sub_teacher_subjects, on: :collection
    get :load_available_teachers, on: :collection
  end
  resources :confirm_substitutions
  resources :generate_reports
  
  resources :remind_substitutes do
    resources :request_details
  end
  
  resources :vouch_requests
  resources :verify_requests
  
  scope '/maintenance' do
    resources :import_schedules, only: [ :index, :create ]
    resources :users
    resources :departments
    resources :teachers
    resources :subjects
    resources :reasons
    resources :daycodes
    resources :sections
    resources :rooms  
    resources :subject_types
  end
  

  

  root :to =>'dashboard#show'

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  

  scope :search_by_name, lambda { |value| where("CONCAT(firstname,' ', lastname) LIKE ?", "%#{value}%") }

  scope :search_by_firstname, lambda { | value | where("firstname LIKE ?", "%#{value}%") }

  scope :search_by_lastname, lambda { | value | where("lastname LIKE ?", "%#{value}%")}

  scope :search_by_phone, lambda { | value | where("phone_number LIKE ?" , "%#{value}%")}


 
  has_many :teacher_subjects
  has_many :substitutes, through: :teacher_subjects
  
  has_many :absents, class_name: :Substitute, foreign_key: :teacher_id
  has_many :absent_reports, class_name: :SubstituteDetail, foreign_key: :teacher_id
  has_many :substitute_reports, class_name: :SubstituteDetail, foreign_key: :substitute_teacher_id

  #has_many :availabilities, class_name: :TeacherAvailability
  
  has_many :subjects, through: :teacher_subjects
  
  validates :lastname, :firstname, presence: true
  validates :phone_number, :length => {:minimum => 6, :maximum => 25},
  						   :format => { :with => /\A\S[0-9\+\/\(\)\s\-]*\z/i },
  						   :allow_blank => true,
  						    uniqueness: { case_sensitivity: true }


  def fullname
    " #{self.lastname}, #{self.firstname}"
  end
  

  def generate_availability
    # fetch all teacher schedules
    # loop each time schedules and plot if its available or not
    # loop for each M T W TH F S
    ["M", "T", "W", "TH", "F", "SA"].each do |day|
      
      # look for list of daycode
      
      daycodes = case day 
                  when "M"
                    DayCode.where("name IN(?)", ["MWF", "MW", "MF", "MTW", "MTWTHF"])
                  when "T"
                    DayCode.where("name IN(?)", ["TTH", "T", "THF", "MTWTHF", "TF"])
                  when "W"
                    DayCode.where("name IN(?)", ["MWF", "MW", "W", "MTW", "MTWTHF"])
                  when "TH"
                    DayCode.where("name IN(?)", ["TTH", "TH", "THF", "MTWTHF"])
                  when "F"
                    DayCode.where("name IN(?)", ["MWF", "F", "MF", "WF", "THF", "TF", "MTWTHF"])
                  when "SA"
                    DayCode.where("name IN(?)", ["SAT"])
                end
      
      self.teacher_subjects.where('day_code_id IN (?)', daycodes.pluck(:id))
                           .find_each do |teacher_subject|
                             
        TimeSchedule.find_each do |time_schedule|
          # 13:00 >= 13:30 && 14:30 <= 14:00
          if ((time_schedule.time_start >= teacher_subject.time_start) && (time_schedule.time_end <= teacher_subject.time_end))
            
            TeacherSchedule.create({ day: day, 
                                     teacher_subject_id: teacher_subject.id,
                                     time_schedule_id: time_schedule.id  })
                                     
          end
          
        end
      end
    
    end
    
  end

  def self.search(search_by, search)

    teacher_scope = self.scoped({})
    case search_by
        when 'Firstname'
           teacher_scope = teacher_scope.search_by_firstname(search)
        when 'Lastname'
            teacher_scope = teacher_scope.search_by_lastname(search)
        when 'Phone Number'
            teacher_scope = teacher_scope.search_by_phone(search)
        end
    return teacher_scope
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
	def index
		#@teachers = Teacher.all

		#@teachers = Teacher.order('firstname').page(params[:id]).per(10)

		# if @teacher.teacher_id = current_teacher_id

		# 	@teachers = @teacher.all ('create_at DESC').paginate(per_page: 1, params[:page])
		# else
		# 	@teachers = current_teacher.teachers(teacher: @teacher, page: params[:page])
		# end
		
		 @teachers = Teacher.search(params[:search_by], params[:search]).page(params[:page]).per(10)
		
	end

	def show
		@teacher = Teacher.find(params[:id])
	end

	def new	
		@teacher = Teacher.new
	end

	def create
		@teacher = Teacher.new(params[:teacher])

		if @teacher.save
			redirect_to teachers_path, notice: "Teacher Successfully Added"
		else
			render :new
		end
	end

	def edit
		@teacher = Teacher.find(params[:id])	
	end

	def update
		@teacher = Teacher.find(params[:id])

		if @teacher.update_attributes(params[:teacher])
			redirect_to teachers_path, notice: "Teacher Successfully Updated"
		
		else
			render :edit
		
		end
	end

	def destroy
	    @teacher = Teacher.find(params[:id])
	    @teacher.destroy

	    redirect_to teachers_path, notice: 'Teacher Deleted!'
  	end

end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<div class="field-group inlineField " style="float:left;">	
	<div class="field">
		<label for="firsname"> Firstname :</label>
		<%= f.text_field :firstname, size: 24, placehold: 'Fistname ' %>
	</div>
	<br/>

	<div class="field">
		<label for="lastname"> Lastname :</label>
		<%= f.text_field :lastname, size: 24, placehold: 'Lastname' %>
	</div>
	<br/>

	<div class="field">
		<label for="phone_number"> Phone number :</label>
		<%= f.text_field :phone_number, size: 24, placehold: 'Phone Number' %>
	</div>
	<br/>
</div>

app/views/teachers/_teacher.html.erb
<tr>
	<td><%= teacher.firstname %></td>
	<td><%= teacher.lastname %></td>
	<td><%= teacher.phone_number %></td>
	<td>
		<%= link_to edit_teacher_path(teacher) do %>
			<button class="btn btn-primary btn-blue">
				Edit
			</button>
		<% end %>
	<div class="delete">
	<%= button_to "delete", teacher_path(teacher), :method=>:delete, :class=>"btn btn-primary btn-blue" %>
	</div>
	</td>	
</tr>

app/views/teachers/edit.html.erb
<div id="content">			
	<div id="contentHeader">
		<h1>Edit Teacher</h1>
	</div> <!-- #contentHeader -->	
	<div class="container">
		<div class="grid-24">
			
			<%= form_for @teacher, :method => :put do |f| %>
			
				<% if @teacher.errors.present? %>
					<div class="alert alert-error">
						<a class="close" href="javascript:;">×</a>

						<% for msg in @teacher.errors.full_messages %>
		          <%= content_tag :div, msg %>
		        <% end %>
							
					</div>
				<% end %>
				
				<div class="form uniformForm">					
					<div class="widget">
						<div class="widget-header">
							<h3>Teacher Information</h3>
						</div>
						<div class="widget-content">
							<%= render 'form', f: f %>
						</div> <!-- .widget-content -->
					</div> <!-- .widget -->
					 
				</div>
				<div class="fmenu">
					<br style="clear:both;">
						
						<%= link_to 'Cancel', teachers_path, class: 'btn btn-primary btn-blue'  %>
						<button class="btn btn-primary btn-blue">Save</button>
				</div>
				
			<% end %>
		</div>
	</div> <!-- .grid -->			
</div>
			
			

app/views/teachers/index.html.erb
<div id="content">			
	<div id="contentHeader">
		<h1>Teachers Information</h1>
	</div> <!-- #contentHeader -->	
	<div class="container">
		<div class="grid-24">
			<% if notice %>
				<div class="alert alert-success">
					<a class="close" href="javascript:;">×</a>
					<%= notice %>
				</div>
			<% end %>

			<div class="adduser">
				<%= link_to new_teacher_path do %>
					<button class="btn btn-primary btn-blue">Add New teacher
					</button>
				<% end %>
				
			</div>

			<div class="widget widget-table">
				<div class="widget-header">
					<h3 class="icon chart">Teachers List</h3>		
				</div>
				
				<div class="widget-content">
					
						<%= form_for teachers_path, method: :get do %>
							<div class="search">
								<div class="field">
									<%= select_tag :search_by, options_for_select(["Firstname","Lastname", "Phone Number"], params[:search_by]) %>
									<%= text_field_tag :search, params[:search] , size: 24, :Placeholder => "Search" %>
									<%= submit_tag "Search", :name => nil, :class => "btn btn-primary btn-blue" %>
								</div> 
							</div>
						<% end %>
					

					<table  id="my-table" class="table table-bordered table-striped data-table">
						<thead>
							<tr>
								<th>Firstname</th>
								<th>Lastname</th>
								<th>Phone Number</th>
								<th>Action</th> 
							</tr>
						</thead>
				   		 <tbody>
				   		 	<%= render partial: 'teacher', collection: @teachers, as: :teacher %>
				    	</tbody>
				    </table>
				    <%= paginate @teachers %>
				</div> <!-- .widget-content -->
			   </div> <!-- .widget -->
			</div> <!-- .widget-content -->
		</div> <!-- .widget -->	
	</div> <!-- .grid -->			
</div>
			
			
<!-- refresh plugin search -->
<script type="text/javascript" src="/assets/jquerysearch.js"></script>

app/views/teachers/new.html.erb
<div id="content">			
	<div id="contentHeader">
		<h1>Create Teacher</h1>
	</div> <!-- #contentHeader -->	
	<div class="container">
		<div class="grid-24">
			
			<%= form_for @teacher, url: teachers_path,  method: :post do |f| %>
			
				<% if @teacher.errors.present? %>
					<div class="alert alert-error">
						<a class="close" href="javascript:;">×</a>
						<% for msg in @teacher.errors.full_messages %>
		          <%= content_tag :div, msg %>
		        <% end %>
					</div>
				<% end %>
				
				<div class="form uniformForm">					
					<div class="widget">
						<div class="widget-header">
							<h3>Teacher Information</h3>
						</div>
						<div class="widget-content">
							<%= render 'form', f: f %>
						</div> <!-- .widget-content -->
					</div> <!-- .widget -->
					 
				</div>
				<div class="fmenu">
					<br style="clear:both;">
						
						<%= link_to 'Cancel', teachers_path, class: 'btn btn-primary btn-blue'  %>
						<button class="btn btn-primary btn-blue">Save</button>
				</div>
			<% end %>
		</div>
	</div> <!-- .grid -->			
</div>
			
			