config/routes.rb
WebBasedTeachersSubstitutionSystem::Application.routes.draw do

  get "confirm_substitutions/index"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  
  resources :sessions

  resources :teacher_schedules
  resources :substitution_records
  resources :substitutes do
    get :load_teacher_subject, on: :collection
    get :load_sub_teacher_subjects, on: :collection
    get :load_available_teachers, on: :collection
  end
  resources :confirm_substitutions
  resources :generate_reports
  
  resources :remind_substitutes do
    resources :request_details
  end
  
  resources :vouch_requests
  resources :verify_requests
  
  scope '/maintenance' do
    resources :import_schedules, only: [ :index, :create ]
    resources :users
    resources :departments
    resources :teachers
    resources :subjects
    resources :reasons
    resources :daycodes
    resources :sections
    resources :rooms  
    resources :subject_types
  end
  

  

  root :to =>'dashboard#show'

end

app/models/substitute.rb
class Substitute < ActiveRecord::Base

  scope :status_is_substitute, where('status = ?', 'Substitute')
  scope :status_is_vouch, where('status = ?', 'Vouch')
  scope :status_is_approved, where('status = ?', 'Approved')
  scope :status_is_pendingsub, where('status = ?', 'Pending Substitute')
  scope :status_is_needtoconfirm, where('status = ?', 'Need to Confirm Substitute')
  scope :request_type_planned, where( planned: true)
  scope :request_type_unplanned, where( planned: false)

  scope :remind_by_date, where( 'request_at_to <= ?', Date.current + 1.day )
  scope :count_remind_by_date, where( 'request_at_to >= ?', Date.current + 1.day )

  scope :search_by_requested, lambda { | value | teachers = Teacher.select('id').where("CONCAT(firstname, lastname) like ? ", "%#{value}%" )
                          self.where("teacher_id IN (?)", teachers.pluck(:id))}

  scope :search_by_substitute, lambda { | value | subs = Teacher.select('id').where("CONCAT(firstname, lastname) like ? ", "%#{value}%" )
                          self.where("substitute_teacher_id IN (?)", subs.pluck(:id))}

  scope :search_by_code, lambda { | value | codes = DayCode.select('id').where("CONCAT(code) like ? ", "%#{value}%" )
                          self.where("subject_id IN (?)", codes.pluck(:id))}


 

  belongs_to :teacher_subject
  belongs_to :teacher
  belongs_to :reason
  
  has_many :details, class_name: :SubstituteDetail
 
  validates :reason_id, :assigned_by_user_id, presence: true

  status = [ "Substitute", "Approved", "Vouch" ]

  # def self.generate_by(start_date)
  #    generate_scope = self.scoped({})  
  #    generate_scope = generate_scope.search_by_created_at(start_date)
  # end

  def request_full_date
    "#{self.request_at_from.strftime('%m-%d-%Y')} - #{self.request_at_to.strftime('%m-%d-%Y')}"
  end
  
  def self.search(search_by, search)
    substitution_records_scope = self.scoped({})
    case search_by

        when 'Requested Teacher'
             substitution_records_scope = substitution_records_scope.search_by_requested(search)
       
    end

    return substitution_records_scope
  end


  def updated_and_generate_for_report
    # loop to date from and date to_a
    
      array_date = (self.request_at_from..self.request_at_to).to_a
      array_date.each do |request_date|
      day = DayCode.day_name_shortcut(request_date.strftime('%a'))
      # get all teacher subject base on daycode
      teacher_scheds = TeacherSchedule.select('DISTINCT teacher_subject_id')
                                      .where( 'day = ? AND teacher_subject_id IN (?)', day, self.details.pluck(:teacher_subject_id) )
      
      self.details.where("teacher_subject_id IN (?)", teacher_scheds.pluck(:teacher_subject_id)).each do |detail|
        
        SubstituteReport.create({ substitute_id: self.id,
                                  teacher_id: self.teacher_id,
                                  teacher_substitute_id: detail.substitute_teacher_id,
                                  teacher_subject_id: detail.teacher_subject_id,
                                  total_hours: detail.teacher_subject.total_hours / 60 / 60,
                                  date_applied: request_date
                                })
        
      end
    end
  end
  
  
  def save_details_breakdown(teacher_schedule, subteacher)
      # "teacher_schedule_id"=>["290", "885", "889"], 
      # "available_teacher"=>["78", "78", "78"]
      
      # loop to date from and date to_a
      array_date = (self.request_at_from..self.request_at_to).to_a
      
      array_date.each do |request_date|
        
        day = DayCode.day_name_shortcut(request_date.strftime('%a'))
      
        # get all teacher subject base on daycode
        teacher_scheds = TeacherSchedule.select('DISTINCT teacher_subject_id')
                                        .where( 'day = ? AND teacher_subject_id IN (?)', day, teacher_schedule)
                                        .includes(:teacher_subject)
        
        teacher_scheds.each do |teacher_sched|
          
          logger.debug teacher_sched.inspect
          
          teacher_subject_index = teacher_schedule.index(teacher_sched.teacher_subject_id.to_s)
          subtitute_teacher_id = subteacher[teacher_subject_index]
          
          if subtitute_teacher_id.present?
          
            self.details.create!({ date_applied: request_date,
                                   teacher_id: teacher_sched.teacher_subject.teacher_id,
                                   substitute_teacher_id: subtitute_teacher_id,
                                   teacher_subject_id: teacher_sched.teacher_subject_id
                                 })
                                 
          end
          
        end
        
        
        # self.details.where("teacher_subject_id IN (?)", teacher_scheds.pluck(:teacher_subject_id)).each do |detail|
        # 
        #   SubstituteReport.create({ substitute_id: self.id,
        #                             teacher_id: self.teacher_id,
        #                             teacher_substitute_id: detail.substitute_teacher_id,
        #                             teacher_subject_id: detail.teacher_subject_id,
        #                             total_hours: detail.teacher_subject.total_hours / 60 / 60,
        #                             date_applied: request_date
        #                           })
        # 
        # end
        
      end
  end
  



  def self.plan_substitute()
    
     results = []

     teachers = self.select('DISTINCT teacher_substitute_id').status_is_needtoconfirm

     Teacher.where("id IN (?)", teachers.pluck(:teacher_substitute_id)).find_each do |teacher|
      approved_substitutes = []
      teacher.substitute_reports.status_is_needtoconfirm.find_each do |report|     
      plan_substitutes << {     created_at: report.date_applied.strftime('%m-%d-%Y'),
                                request_at: report.date_applied.strftime('%m-%d-%Y'),
                                substituted_by: report.teacher.fullname,
                                subject_time: report.teacher_subject.start_end_time_daycode,
                                total_hours: report.total_hours
                              }
      end
      
      if plan_substitutes.present?

        results << { name: teacher.fullname, 
                     approved_substitutes: plan_substitutes,
                     total_hours: approved_substitutes.map{ |p| p[:total_hours] }.sum 
                   } 
      end
    end

    return results
  end


  
end

app/controllers/substitutes_controller.rb
class SubstitutesController < ApplicationController
  
  def index

    @substitutes = Substitute.request_type_planned.status_is_substitute.search(params[:search_by],params[:search]).page(params[:page]).per(10)
  

   end
  
  def show
    @substitute = Substitute.find(params[:id])
  end
  
  def new
    @substitute = Substitute.new
  end

  def create
    # { "utf8"=>"✓", "authenticity_token"=>"4GpSZ/8OvQinBB45RyN8H0RJfecH/8vJLmLXOjMW5O4=", 
    #   "planned"=>"false", "absent_teacher"=>"1", 
    #   "teacher_schedule_id"=>["17", "966", "776", "1348", "1", "129", "193", "177", "201", "924", "948", "978", "105"], 
    #   "available_teacher"=>["78", "", "", "", "", "", "", "", "", "", "", "", ""], "reason"=>"1", 
    #   "notes"=>"", "request_at_from"=>"10/15/2012", "request_at_to"=>"10/19/2012" }
    
    request_at_from = params[:request_at_from]
    request_at_to = params[:request_at_to].present? ? params[:request_at_to] : request_at_from
    
    @substitute = Substitute.new({ request_at_from: request_at_from,
                                   request_at_to: request_at_to,
                                   planned: params[:planned],
                                   reason_id: params[:reason],
                                   teacher_id: params[:absent_teacher],
                                   assigned_by_user_id: current_user.id
                                })
                                    
    if params[:planned] == "false"
            @substitute.status = 'Pending Substitute'
    else
            @substitute.status = 'Need to Confirm Substitute'
    end
    
    if @substitute.save
        @substitute.save_details_breakdown(params[:teacher_schedule_id], params[:available_teacher])
    else
      logger.debug @substitute.errors.inspect
    end
    
    redirect_to confirm_substitutions_path, :notice => "Successfully Requested"
  
  end

  def edit
    @substitute = Substitute.find(params[:id]) 
  end

  def update
    
        @substitute = Substitute.find(params[:id])
        
        verifyer_status = if params[:commit] == 'Confirm'; 'Void'
                         else; 'Void'; end
        
        @substitute.update_column(:status, verifyer_status)
        
        redirect_to substitutes_path, notice: "Request is being Void!!"
      
  end
    
  def destroy
    @substitute = Substitute.find(params[:id])
    @substitute.destroy
    redirect_to substitutes_path, :notice => "Request Successfully Deleted" 
  end
  
  
  def load_teacher_subject
    teacher = Teacher.find(params[:teacher_id])
    @subjects = teacher.teacher_subjects
                       .order("day_code_id, time_start").includes(:subject, :day_code)    
  end
  
  def load_sub_teacher_subjects
    teacher = Teacher.find(params[:sub_teacher_id])
    @subjects = teacher.teacher_subjects.includes(:subject, :day_code)
  end
  
  
  def load_available_teachers
    # get info for time and daycode and subject
    teacher_subject = TeacherSubject.find(params[:teacher_subject_id])
      
    @available_teachers = teacher_subject.fetch_available_teacher
  end
  
  
  

end

app/views/substitutes/_absentteacher.html.erb
<tr>
	<th><%= teacher.lastname %></th>
	<th><%= teacher.firstname %></th>
	<th>
		<button class="btn btn-primary btn-blue">
			<span class="icon-user"></span>
			select
		</button>
	</th>
</tr>

app/views/substitutes/_available_teacher.html.erb
<tr>
	<td><%= available.teacher.fullname %></td>
	<td><%= available.subject.name %></td>
	<td><%= available.start_end_time_daycode %></td>
	<td></td>
</tr>

app/views/substitutes/_form.html.erb
<div class="widget widget-table">
	<div class="widget-header">
	<h3 class="icon chart">Substitution Information</h3>
	</div>

	<div class="alert alert-error" style="display: none"></div>
	
	<%= form_tag substitutes_path, id: 'create-substitute-form', method: :post do %>
	
		<div class="widget-content">
			<div class="grid-24">
				
				<div class="form" style="width:400px; ">
					<div class="field">
						<label>Request Type :</label>
						<%= select_tag :planned, options_for_select([["Unplan", false], ["Plan", true]]) %>					
					</div>

				</div>
				<div class="form" style="width:400px; float:left;">

					<div class="field">
						<label>Request Teacher :</label>
						<%= text_field_tag :absent_teacher, :style => "width:100px;" %>
					</div>

				</div>
				<br style="clear:both;"/>
			</div>
		</div>

		<br/>
		<div class="grid-24">
			<h3 class="icon chart">Selected Teacher Subjects</h3>
			
			<table id="select-teacher-subjects-table" class="table table-bordered table-striped data-table">
				<thead>
					<tr>
						<th width="50%">Subject Information</th>
						<th>Schedule</th>
						<th>Available Teacher</th>
					</tr>
				</thead>
				<tbody></tbody>
		</table>
		</div>

		<div class="grid-24">
			<div class="form" style="width:400px; float:left;">
				<div class="field">
					<label>Reason :</label>
					<%= select_tag :reason, options_for_select(Reason.all.collect { |u| [u.name, u.id] }) %>
				</div>
				<div class="field">
					<label>Notes :</label>
					<%= text_area_tag :notes %>
				</div>
			</div>

			<div class="form" style="width:400px; float:left;">
				<div class="field">
					<label>Start Request Date:</label>
					<%= text_field_tag :request_at_from, nil, class: 'datepicker' %>
				</div>

				<div class="field request_at_to" style="display:none">
					<label class="request_at_to">End Request Date:</label>
					<%= text_field_tag :request_at_to, nil, class: 'datepicker' %>
				</div>
			</div>
			<br style="clear:both;"/>
		</div>
		<div class="fmenu">
			<br style="clear:both;">
			
				<%= link_to 'Cancel', new_substitute_path, class: 'btn btn-primary btn-blue'  %>
				<button class="btn btn-primary btn-blue">Save</button>
		</div>
		
	<% end %>
	
	<br style="clear:both;"/>
	<br style="clear:both;"/>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		
		var request_type = 'unplan';
		
		$('#planned').change(function(){
			if($(this).val() == 'false'){
				request_type = 'unplan';
				$('.request_at_to').hide();
			}else{
				request_type = 'plan';
				$('.request_at_to').show();
			}
		})
		
		$("form").submit(function() {
			 // check if form has all the required field
			var proceed = true;
			var select_box_proceed = false;
	
			$('.alert').html("");
	
			 // check if has selected teacher
			if($('#absent_teacher').val() == ''){
				$('.alert').append("Please select a requester teacher <br />");
				proceed = false;
			}
			
			if(request_type == 'plan'){
				
				if($('#request_at_from').val() == '' || $('#request_at_to').val() == ''){
					$('.alert').append("Please fill up request date from and to <br />");
					proceed = false;
				}
				
			}else{
				
				if($('#request_at_from').val() == ''){
					$('.alert').append("Please fill up request date from<br />");
					proceed = false;
				}
				
			}
			
			
			// check each select box if not empty
			if($('.available-teacher-options')){
				
				$('.available-teacher-options').each(function(){
				
					if(!select_box_proceed && $(this).val() != "" ){
						select_box_proceed = true;
					}
				})
						
				if(!select_box_proceed){
					$('.alert').append("Please select one or more subject!");
					proceed = false;
				}
			
			}
			
			
			if(!proceed){ $('.alert').show() }
		  

			return proceed;
		});
		
		$( ".datepicker" ).datepicker({
											numberOfMonths: 2,
											showButtonPanel: true,
											changeMonth: true,
											changeYear: true,
											dateFormat: 'yy/mm/dd'
										});
		
	})

</script>

app/views/substitutes/_form1.html.erb
<br />

<ul class="nav nav-tabs" id="myTab">
  <li class="active"><%= link_to 'Select Teacher And Subject', '#step1', id: 'step1-tab' %></il>
  <li><%= link_to 'Select Teacher to Substitute', '#step2', id: 'step2-tab' %></li>
  <li><%= link_to 'More Details', '#step3', id: 'step3-tab' %></li>
</ul>
 
<div class="tab-content">
  <div class="tab-pane active" id="step1"><%= render 'substitutes/form/step1' %></div>
  <div class="tab-pane" id="step2"><%= render 'substitutes/form/step2' %></div>
  <div class="tab-pane" id="step3"><%= render 'substitutes/form/step3' %></div>
</div>
 
<script type="text/javascript" charset="utf-8">
	$(document).ready(function(){
		
		$('#myTab a').click(function (e) {
		  e.preventDefault();
		  $(this).tab('show');
		})
			
	})
</script>

app/views/substitutes/_show_substitute.html.erb
<div class="form uniformForm">					
	<div class="widget">
		<div class="widget-content">
			
			<div class="widget-sheader">
				<div style="float:left">	
					<h5>Date Request By :&nbsp&nbsp</h5>
				</div>
				<div style="float:left">
					<h4><%= @substitute.teacher_subject.created_at.strftime('%D') %></h4>
				</div>
				<br style="clear:both;"/>
				<div style="float:left">	
					<h5>Substitute By :&nbsp&nbsp</h5>
				</div>
				<div style="float:left">
					<h4><%= @substitute.substitute_teacher.fullname %></h4>
				</div>

				<br style="clear:both;"/>
			<div>
				<div style="float:left">
					<h5>Absent Teacher:&nbsp&nbsp</h5>
				</div>
				<div style="float:left">
					<h4><%= @substitute.teacher_subject.teacher.fullname %><h4>
				</div>
			</div>
			<br style="clear:both;"/>
			<div>
				<div style="float:left">
					<h5>Subject Code:&nbsp&nbsp</h5>
				</div>
				<div style="float:left">
					<h4><%= @substitute.teacher_subject.subject.code %><h4>
				</div>
			</div>
			<br style="clear:both;"/>
			<div>
				<div style="float:left">
					<h5>Room Number:&nbsp&nbsp</h5>
				</div>
				<div style="float:left">
					<h4><%= @substitute.teacher_subject.room.name %><h4>
				</div>
			</div>

			<br style="clear:both;"/>
			<div>
				<div style="float:left">
					<h5>Section:&nbsp&nbsp</h5>
				</div>
				<div style="float:left">
					<h4><%= @substitute.teacher_subject.section.name %><h4>
				</div>
			</div>

			<br style="clear:both;"/>
			<div>
				<div style="float:left">
					<h5>Time Start :&nbsp&nbsp</h5>
				</div>
				<div style="float:left">
					<h4><%= @substitute.teacher_subject.time_start.strftime('%l: %m %p') %><h4>
				</div>
			</div>

			<br style="clear:both;"/>
			<div>
				<div style="float:left">
					<h5>Time End:&nbsp&nbsp</h5>
				</div>
				<div style="float:left">
					<h4><%= @substitute.teacher_subject.time_end.strftime('%l: %m %p') %><h4>

				</div>
			</div>

			<br style="clear:both;"/>
			<div>
				<div style="float:left">
					<h5>Schdule:&nbsp&nbsp</h5>
				</div>
				<div style="float:left">
					<h4><%= @substitute.teacher_subject.day_code.name %><h4>
						
				</div>
			</div>
		</div> <!-- .widget-content -->
	</div> <!-- .widget -->
</div>

app/views/substitutes/_subject.html.erb
<tr>
																			
	<td>
		<h3><%= subject.subject.name %></h3>
		<div style="clear:both;text-align:center;">
			<div  style="float:left;margin-left:8px; margin-left:20px;">
				Subject Code:<%= subject.subject.code %> /
			</div>
			<div style="float:left;margin-left:8px;">
				Room #:<%= subject.room.name %> /
			</div>
			<div style="float:left;margin-left:8px;">
				Section<%= subject.section.name %> /
			</div>
			<div style="float:left;margin-left:8px;">
				Type:<%= subject.subject_type.name %>	
			</div>
		</div>
	</td>
	<td><%=  subject.start_end_time_daycode %></td>
	<td>
		<%= hidden_field_tag 'teacher_schedule_id[]', subject.id %>
		<%= select_tag "available_teacher[]", 
						options_from_collection_for_select(subject.fetch_available_teacher, :id , :fullname),
						prompt: 'Select a Teacher', class: 'available-teacher-options' %>

	</td>
</tr>

app/views/substitutes/_substitute.html.erb
<tr>
	<th><%= substitute.created_at.strftime('%m-%d-%Y') %></th>
	<th><%= substitute.teacher_subject.teacher.fullname %></th>
	<th><%= substitute.substitute_teacher.fullname %></th>
	<th><%= substitute.teacher_subject.subject.code %></th>
	<th><%= substitute.teacher_subject.room.name %></th>
	<th><%= substitute.teacher_subject.section.name %></th>
	<th><%= substitute.teacher_subject.subject_type.name %></th>
	<th><%= substitute.teacher_subject.time_start.strftime('%l: %m %p') %></th>
	<th><%= substitute.teacher_subject.time_end.strftime('%l: %m %p') %></th>
	<th><%= substitute.teacher_subject.day_code.name %></th>
	<th><!-- 
			<%= link_to 'Void', substitute_path(substitute), method: :get , :class => "btn btn-primary btn-blue",data: { confirm: 'Are you sure you want to Vouch this Request?' } %> -->

			<%= link_to 'Show', substitute_path(substitute), method: :get , :class => "btn btn-primary btn-blue" %>
	 
	</th>
</tr>	

app/views/substitutes/_teacher.html.erb
<%= content_tag :tr, id: teacher, data: { id: teacher.id, name: teacher.fullname } do %>
	<th><%= teacher.lastname %></th>
	<th><%= teacher.firstname %></th>
	<th>
		<button class="btn btn-primary btn-blue">
			Select
		</button>
	</th>
<% end %>

app/views/substitutes/create.js.erb
<% if @substitute.save  %>
  	window.location = "<%= substitutes_path %>";
<% else %>
  <% logger.debug @substitute.inspect %>
<% end %>

app/views/substitutes/index.html.erb
	<div id="content">			
	<div id="contentHeader">
		<h1>All Request Teachers</h1>
	</div> <!-- #contentHeader -->	

	<div class="container">
		<div class="grid-24">
			
			<% if notice %>
				<div class="alert alert-success">
							<a class="close" href="javascript:;">×</a>
							<%= notice %>
				</div>
			<% end %>
			<div class="adduser">
				<a href="<?php echo base_url();?>index.php/substitution/request">
					<%= link_to new_substitute_path do %>
						<button class="btn btn-primary btn-blue">Request New Substitution
						</button>
					<% end %>
				</a>
			</div>
			<div class="widget widget-table">
				<div class="widget-header">
					<h3 class="icon chart">Substitute Information</h3>		
				</div>
				<div class="widget-content">
					<%= form_for subjects_path, method: :get do %>
							<div class="search">
								<div class="field">
									
									<%= text_field_tag :search, params[:search], size: 24 , :Placeholder => "Search" %>
									<%= submit_tag "Search", :name => nil, :class => "btn btn-primary btn-blue" %>	
								</div>
							</div>
					<% end %>
					<table  id="my-table" class="table table-bordered table-striped data-table">
						<thead>
							<tr>
								<th>Date Request</th>
								<th>Requested Teacher</th>
								<th>Substitute Teacher</th>
								<th>Subject Code</th>
								<th>Room #</th>
								<th>Section</th>
								<th>Type</th>
								<th>Start Time</th>
								<th>End Time</th>
								<th>Schedule</th>
								<th>Options</th>
							</tr>
						</thead>
				        <tbody>
							<%= render partial: 'substitute', collection: @substitutes, as: :substitute %>

				        </tbody>
			         </table>
			         <%= paginate @substitutes %>
				</div> <!-- .widget-content -->
			   </div> <!-- .widget -->
			</div> <!-- .widget-content -->
		</div> <!-- .widget -->	
	</div> <!-- .grid -->			
</div>

			
			
			

app/views/substitutes/load_available_teachers.js.erb
$("#available-teachers-table tbody").html("<%= escape_javascript(render partial: '/substitutes/available_teacher', collection: @available_teachers, as: :available) %>");

app/views/substitutes/load_sub_teacher_subjects.js.erb
$("#sub-teacher-subjects-table tbody").html("<%= escape_javascript(render partial: '/substitutes/sub_teacher_subjects', collection: @subjects, as: :subject) %>");

app/views/substitutes/load_teacher_subject.js.erb
$("#select-teacher-subjects-table tbody").html("<%= escape_javascript(render partial: '/substitutes/subject', collection: @subjects, as: :subject) %>");

app/views/substitutes/show.html.erb
<div id="content">			
	<div id="contentHeader">
		<h1>Substitute Information</h1>
	</div> <!-- #contentHeader -->	
	<div class="container">
		<div class="grid-24">
			<% @subject.inspect %>
			<%= form_for @substitute, :method => :put do |f| %>

				<%= render :partial => "show_substitute" %>
				
				<br /><br /><br />
				<div class="form-actions" id="final-confirmation-btn">
					<div class="pull-right">
				<%= link_to 'Cancel', substitutes_path, class: 'btn btn-primary btn-blue'  %>
													&nbsp;&nbsp;&nbsp; 
				<%= f.submit 'Void Request', class: 'btn btn-primary btn-blue', 
													data: { confirm: 'Are you sure you want to Viod This Request?' } %>
													&nbsp;&nbsp;&nbsp; 
				
					</div>
				</div>
				
			<% end %>
		</div>
	</div> <!-- .grid -->			
</div>
			
			